export const genres = [
    'Christian Rock',
    'Christian Rap',
    'Gospel',
    'R & B',
    'Pop',
    'Christian Country',
    'Lifestyle & Health',
    'Reggae',
    'TV',
    'Rap',
    'Alternative',
    'Blues',
    'World',
    'Indie',
    'Easy Core',
    'Dancehall',
    'Electronic',
    'Latin',
    'Funk',
    'Classical',
    'Instrumental',
    'Country',
    'Carribean',
    'Punk',
    'Soul',
    'Metal',
    'Political',
    'Arts & Entertainment',
    'Business & Technology',
    'Music',
    'Sports',
    'Entertainment',
    'Self Improvement',
    'News',
    'Books',
    'Education',
    'Video Games',
    'Alternative Facts',
    'Stories',
];