export const genres = [
    "A Capella",
    "Acoustic",
    "Adventure",
    "African",
    "Arab",
    "Art",
    "Alternative Rock",
    "Bass Music",
    "Beats",
    "Biblical",
    "Biography",
    "Bluegrass",
    "Blues",
    "Business",
    "Childrens",
    "Church Leadership",
    "Comedy",
    "Cooking",
    "Counseling",
    "Country",
    "Crunk",
    "Dance",
    "Dancehall",
    "Devotionals",
    "Easycore",
    "EDM",
    "Education",
    "Entertainment",
    "Evangelism",
    "Folk",
    "Footwork",
    "Freestyle",
    "Funk",
    "Fiction",
    "Giving",
    "Gospel",
    "Grunge",
    "Hard Rock",
    "Harp",
    "Hawaiian",
    "Health",
    "Hip Hop",
    "Indie",
    "Israeli",
    "Irish",
    "Jazz",
    "Jerk",
    "Latin",
    "Lifestyle",
    "Mental Health",
    "Metal",
    "Music",
    "News",
    "Politics",
    "Pop",
    "Punk",
    "R&B",
    "Rap",
    "Reggae",
    "Relationships",
    "Rock",
    "Romantic",
    "Salsa",
    "Sermons",
    "Sports",
    "Technology",
    "Television",
    "Underground",
    "Video Games",
    "Zydeco",
];