export type ArtistType = {
    firstName: string;
    lastName: string;
    artistName: string;
    birthday: number;
    createdOn: number;
    downVotes?: [{ fanId: string; swipeDate: number }];
    downVoteCount?: number;
    upVotes?: [{ fanId: string; swipeDate: number }];
    upVoteCount?: number;
    email: string;
    fans: [{ fanAvatar: string; fanId: string; fanName: string; }];
    gender: any;
    genres: [string];
    username: string;
    password: string;
    phoneNumber: string;
    soundcloudLink?: string;
    youtubeLink?: string;
    spotifyLink?: string;
    city: string;
    state: string;
    subscribers: [string];
    userType: string;
    bio?: string;
};